e2e: add check for actual sync status for both clusters

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -93,6 +93,8 @@ jobs:
           kubectl wait pods -l app.kubernetes.io/name=cluster-registry-controller --timeout=120s --for condition=Ready -n cluster-registry --kubeconfig $KUBECONFIG2
           kubectl get pods -A --kubeconfig $KUBECONFIG1 > ${ARTIFACTS_DIR}/pods_c1.txt
           kubectl get pods -A --kubeconfig $KUBECONFIG2 > ${ARTIFACTS_DIR}/pods_c2.txt
+          kubectl get secrets -A --kubeconfig $KUBECONFIG1 > ${ARTIFACTS_DIR}/secrets_c1.txt
+          kubectl get secrets -A --kubeconfig $KUBECONFIG2 > ${ARTIFACTS_DIR}/secrets_c2.txt
           kubectl get clusters -o yaml  --kubeconfig $KUBECONFIG1
           kubectl get clusters -o yaml  --kubeconfig $KUBECONFIG2
           echo "Getting cluster c1"
@@ -112,13 +114,17 @@ jobs:
           sync2=$(kubectl get clusters -A --kubeconfig $KUBECONFIG2 -o jsonpath='{range .items[*]}{@.status.conditions[?(@.type=="ClustersSynced")].status}{end}')
           echo "Cluster 2 sync status = ${sync2}"
           if [[ "${sync1}" == "" || "${sync2}" == "" ]]; then
-            echo "one or more clusters not in sync"
+            echo "one or more clusters missing sync status"
             exit 1
           fi
           sync_reason1=$(kubectl get clusters -A --kubeconfig $KUBECONFIG1 -o jsonpath='{range .items[*]}{@.status.conditions[?(@.type=="ClustersSynced")].reason}{end}')
-          sync_reason2=$(kubectl get clusters -A --kubeconfig $KUBECONFIG1 -o jsonpath='{range .items[*]}{@.status.conditions[?(@.type=="ClustersSynced")].reason}{end}')
+          sync_reason2=$(kubectl get clusters -A --kubeconfig $KUBECONFIG2 -o jsonpath='{range .items[*]}{@.status.conditions[?(@.type=="ClustersSynced")].reason}{end}')
           echo "Sync status reason 1 = '${sync_reason1}'"
-          echo "Sync status reason 1 = '${sync_reason2}'"
+          echo "Sync status reason 2 = '${sync_reason2}'"
+          if [[ "${sync1}" == "False" || "${sync2}" == "False" ]]; then
+            echo "one or more clusters are not in sync"
+            exit 1
+          fi
         working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
         env:
           ARTIFACTS_DIR: ${{ github.workspace }}/test_artifacts
